Portfolio: desktop version: day 2
normainobary2021/my-portfolio pull request #5
Opened 2022-07-07 18:12 UTC by normainobary2021

In this pull request I have added the following changes:
- Edited index.html to adopt for the Desktop version of my-portfolio
- Added media query styling in style.css for Responsive Web Design
- Added images fit for the Desktop version

2022-07-07 19:42 UTC, mirouhml requested changes
# REQUIRED CHANGES 🔴

Hi @normainobary2021, 

Good job so far!

There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media4.giphy.com/media/KyBesf8kNT6s88SEgb/giphy.gif?cid=ecf05e47n6s5huda7qh40syoppcaspe9vx68ddmxerd08owm&rid=giphy.gif&ct=g)

## Highlights

- Great job setting up the correct linters ✔️
- Highly organized and clean code ✔️ 👨🏻‍💻
- Professional documentation ✔️
- Correct workflow ✔️
- Meaningful commit messages ✔️

## Required Changes ♻️
_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-07 19:42 UTC, mirouhml commented on style.css
> +  }
- [ ] Please know that you shouldn't fix the width of the sections you have, you'll have to use flexbox and grid to align them and make them responsive without the need to fix any width or height, check how the design looks right now:

![image](https://user-images.githubusercontent.com/20567503/177857054-0657affc-9fa4-4506-8d85-2c992c59adc1.png)
![image](https://user-images.githubusercontent.com/20567503/177857092-d9af0de7-2329-41d0-853c-7cccbf28a1de.png)

Kindly fix the issues so your design matches the [Figma design](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=39%3A122).

2022-07-07 19:42 UTC, mirouhml commented on style.css
>    background-color: var(--background);
- [ ] You shouldn't fix the width of the mobile version, it should be responsive for screens that have a width range of `375px` to at least `768px`, this is how it looks right now:

![image](https://user-images.githubusercontent.com/20567503/177857586-7f6f398e-e9af-406c-8f5b-22d61355f4ac.png)

Kindly fix this for the body and for the works section because the grid container has a fixed column width too, this will help make your website responsive for mobile and desktop screens. 😁

2022-07-07 19:42 UTC, mirouhml commented on style.css
> +  }
- [ ] Same comment for this one, kindly don't fix the width of any section, you should make it responsive for all sizes. 😄

This caused this issue:

![image](https://user-images.githubusercontent.com/20567503/177858560-1964437f-0d61-46c7-aa25-8d28f931eec3.png)

2022-07-08 18:20 UTC, mmsesay requested changes
Hi @normainobary2021, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
 - Good Readme :heavy_check_mark: 
 - No linter error :heavy_check_mark: 
 - Good PR title :heavy_check_mark: 
 - PR summary :heavy_check_mark:  

 ## Required Changes ♻️
_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-08 18:20 UTC, mmsesay commented on style.css
>  }
- [ ] The responsiveness of the site breaks at some screen sizes. I will suggest you take into consideration removing the widths that you set for specific sections just as mentioned by the previous reviewer's [comment](https://github.com/normainobary2021/my-portfolio/pull/5#discussion_r916217297). Setting the widths will cause responsive issues. 

Please a gif of the demo I ran on your site. Please do take note of the areas where I moved my mouse cursor frequently.  They are the sections that break out and some do overlap. Like the languages in the about section.

Demo |
:----------------:|
![a1](https://user-images.githubusercontent.com/39523312/178048519-900bf908-ac84-40cf-b081-d83e6e68bdad.gif)

2022-07-09 18:32 UTC, Reem-lab approved these changes
## Hi @normainobary2021, 👋🏻👋🏻 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
<img src="https://media4.giphy.com/media/3oEjI5VtIhHvK37WYo/giphy.gif"/>

## Highlights🔥🔥
- No Linters error ✅✅
- Great job working on requested changes✅✅
- Good GitHub flow✅✅

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-09 18:40 UTC, normainobary2021 commented
Thank you all for the encouragement. I am happy to learn :)

2022-07-09 18:41 UTC, merged