Portfolio: details popup window PR
normainobary2021/my-portfolio pull request #9
Opened 2022-07-22 10:19 UTC by normainobary2021

In this PR I have made the following changes:
- Modified index.html to include popup screen elements for both mobile and desktop
- Modified style.css to include necessary styling for new popup screen functionality
- Modified main.js to include dynamic page rendering functionality for the popup window feature
- Added new background images for the hyperlink buttons.

2022-07-22 11:31 UTC, ishimwezachee requested changes
Hi @normainobary2021 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<img src="https://media3.giphy.com/media/z3piokwf0WPH81MOhu/giphy.gif"/>

## Highlights
Linters are passing 👍 
Project is running successfully 👍 
PR is well described 👍 


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-22 11:31 UTC, ishimwezachee commented on main.js
> +
- [ ]  Your popup card should follows the design for both desktop and mobile versions from [the chosen template in Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1) such as  font, colours, images, text, margins.

Figma design             |  Your design
:-------------------------:|:-------------------------:
![image](https://user-images.githubusercontent.com/43877689/180428720-1e6de2c8-9917-4ade-8843-55fa09cb8022.png)  |  ![image](https://user-images.githubusercontent.com/43877689/180429223-494acfda-77d2-41d4-80f3-946d38e9f61d.png)

2022-07-22 11:31 UTC, ishimwezachee commented on main.js
> +  popupDiv.className = 'overlay';
- [ ]  Your button should have the size similar to the one from the Figma design
![image](https://user-images.githubusercontent.com/43877689/180429709-60364401-707e-4853-b740-bb5c694a5459.png)
![image](https://user-images.githubusercontent.com/43877689/180429987-48f80dc7-2deb-4be1-a1ad-28d43b081bc5.png)

2022-07-22 19:38 UTC, leonardodiasb requested changes
# Required Changes ♻️ ⚠️ 🚦 

Hi @normainobary2021 , 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

![mario_ladders](https://user-images.githubusercontent.com/20563252/121369265-4e418880-c901-11eb-848c-1eff06d5a4cf.gif)

## Good points 👍 
...
You used proper GitHub Flow ✔️
Your linter checks are all passing ✔️
Your README and PR message are descriptive ✔️

## Aspects to improve ♻️

- [x] Check the comments under the review.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-22 19:38 UTC, leonardodiasb commented on style.css
> +
- [ ] You did a great job fixing the position of your desktop popup but it still looks very off from the Figma template. Kindly try to follow the Figma design as much as possible. Your popup design has some issues like the background is a little bit transparent, the paddings of the desktop tech tags are no matching, the paddings of your mobile 'See Live'/'See Source' buttons are not matching, the image sizing in the mobile design is off, etc...
Your design:
<img width="423" alt="Screen Shot 2022-07-22 at 4 24 53 PM" src="https://user-images.githubusercontent.com/61919617/180515069-fe73fb8f-f4d6-4112-96e7-2e8a902f1ed0.png">
<img width="1412" alt="Screen Shot 2022-07-22 at 4 24 22 PM" src="https://user-images.githubusercontent.com/61919617/180515310-0ca54118-0073-44a6-95fc-b4be88d6eac7.png">

2022-07-23 15:28 UTC, Munsa1 approved these changes
Hi @normainobary2021, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
:heavy_check_mark: Descriptive Readme
:heavy_check_mark: Passing Linters
:heavy_check_mark: Correct Gitflow

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-23 16:05 UTC, normainobary2021 commented
Thank you @Munsa1, @leonardodiasb and @ishimwezachee for your kind reviews. I appreciate every bit of it

2022-07-23 16:05 UTC, merged